### ISSUE TITLE
error in raw not found in main activity

### ISSUE THREAD

**Issue by georgethomas2015e** [Cloudoki/android-google-cloud-speech-api#4]
it could not find the raw in the code which created the error at compile time , and also where do i put my speech api key , i simply want to convert voice to text with all the language supported listed in google translation api, thanks.

**Comment by rameshvoltella** [comment]
thats the raw file the json file we get from google console

check this link to know how to generate the file
https://cloud.google.com/docs/authentication/getting-started#creating_the_service_account
after getting json put it on raw thats it
